### ISSUE TITLE
classes on input element is removed on initialising

### ISSUE THREAD

**Issue by ghost** [LCweb-ita/LC-switch#1]
The class 'test_class' on this 'input' element is getting ridden after calling the 'lc_switch() method'.

<input type="checkbox" name="check-1" value="4" class="lcs_check test_class " autocomplete="off" />

It is not possible to do proper styling if this is the case. You guyz should copy the class as well to the toggle button.

**Comment by LCweb-ita** [comment]
Hi, thanks for the suggestion, but I'd like to understand better pro sides of this.

Since field status changes are reflected in real time and original checkbox is always kept (but hidden), don't see any advantage of copying (then doubling) classes also  on switch.

**Comment by ghost** [comment]
I have many options and for each option, there are 2 categories. So, I decide to do UX like this.

```
                              Notification1                    Notification2
```

Option 1                                                  On/Off                            On/Off

Option 2                                                  On/Off                            On/Off

etc..

So, i need to give style to each elements. I tried by putting the style on input element assuming the common behaviors of widgets. Obviously, it didn't work out. I had to select the element in css like this
div.lcs_wrap:nth-child(1){
    float: left;
    width: 200px;
}
div.lcs_wrap:last-child(2){
    float: left;
}

I hope you got me.

**Comment by LCweb-ita** [comment]
Being a styling matter: wouldn't be cleaner to wrap those fields with differengt elements?

``` html
<div class="row1"><input type="checkbox" /></div>
<div class="row1"><input type="checkbox" /></div>

<div class="row2"><input type="checkbox" /></div>
<div class="row2"><input type="checkbox" /></div>
```

I use prefer to not add custom CSS to switches and use a similar solution in my WP plugins.
Doubling classes is never a good idea in my opinion. Maybe a custom attribute to set custom classes to switch wrapper would be better, what do you think?
