### ISSUE TITLE
onclick event

### ISSUE THREAD

**Issue by xgregg** [LCweb-ita/LC-switch#10]
Sometimes there are differences between setting the state programmatically (eg on initialization) and setting the state on click. My application sets the initial state based on values from database but I need to change it based on parameters. The problem is that there is only one event so I can not distinguish between them.
Any easy way to agregate an onclick event?

**Comment by LCweb-ita** [comment]
There are API functions to manage statuses on the fly. 
After your software sets the check status, just use a little script like this one:

`($('input').is(':checked')) ? $('input').lcs_on() : $('input').lcs_off();`
