### ISSUE TITLE
jQuery Ui

### ISSUE THREAD

**Issue by ltdeta** [LCweb-ita/LC-switch#13]
Hi,
is a theme support planned?

**Comment by LCweb-ita** [comment]
Hi, do you mean CSS files to change its aspect?

**Comment by ltdeta** [comment]
yes

**Comment by LCweb-ita** [comment]
It has already been made to be styled in 2 minutes : is totally CSS based and the CSS file is just 100 lines long.

Then you just need to create your own file: https://github.com/LCweb-ita/LC-switch/blob/master/lc_switch.css

**Comment by ltdeta** [comment]
ok
