### ISSUE TITLE
Is it possible to theme only one checkbox on a page ?

### ISSUE THREAD

**Issue by ghost** [LCweb-ita/LC-switch#3]
Hi,

I'd like to use your switches for a webpage of mine, but I can't make it work on only a specific checkbox and not all of them.

If you have any clue, that would be a great help !

Thank you.

Sincerly

**Comment by LCweb-ita** [comment]
Hi, just use a selector for that specific check. Basically add a class or an id to that input and use 

```
$('.the_check_class').lc_switch();
```
