### ISSUE TITLE
Typo on the homepage

### ISSUE THREAD

**Issue by snipe** [LCweb-ita/LC-switch#4]
Hi - thanks for this great plugin! I forked it absent-mindedly because I thought the homepage for it was in the git repo and I was going to create a PR, but I realize it's not. You have a small typo in your docs.

![screen shot 2015-06-16 at 7 01 17 pm](https://cloud.githubusercontent.com/assets/197404/8198363/3c23058c-145a-11e5-8513-f56549c78199.png)

`onsole.log` should be `console.log`

Thanks again!

**Comment by LCweb-ita** [comment]
Ops.. fixed! Thanks :)
