### ISSUE TITLE
Resizing the switch

### ISSUE THREAD

**Issue by wrongangle** [LCweb-ita/LC-switch#5]
Is there a dynamic way of resizing the switch as I need to different sizes.

**Comment by LCweb-ita** [comment]
Hi there, no, it must have fixed sizes since could be placed also in containers not having a "CSS readable" width. 

Then just create a custom CSS code targeting smaller checks and set smaller sizes (only few CSS lines are needed)

**Comment by wrongangle** [comment]
Thanks for the reply.

I am trying to make the height smaller.
Can you tell me which lines to change and how to work out the calculations.

Cheers.
