### ISSUE TITLE
jQuery's delegated becomes deprecated...

### ISSUE THREAD

**Issue by kylescousin** [LCweb-ita/LC-switch#6]
$('body').delegate('.lcs_check', 'lcs-on', ...) does not seem to do anything. It's still in the documentation likes this. Alternative?

**Comment by LCweb-ita** [comment]
Hi, I know is deprecated, but a lot of people still uses old jQuery versions, then is the safest way. I will replace it with on() in future. You can already use it to handle events though! 

However issue isn't surely the delegate function, give a try using _$(document)_ as initial selector.

**Comment by M4nimal** [comment]
Please could you provide a solution for this, I literally use LC SWITCH on all my projects, I really dont want to find a replacement..

**Comment by LCweb-ita** [comment]
Hi guys, finally I had time to update the script.
Issue solved on v1.1 (b111a66)
