### ISSUE TITLE
Addon-reviewers security risk

### ISSUE THREAD

**Issue by netquik** [LCweb-ita/LC-switch#9]
Hi i use your lib in an browser extension i wrote. Mozilla AMO reviewers rejected the add-on for some reasons among which: 

This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk. For more information, see https://developer.mozilla.org/en/XUL_School/DOM_Building_and_HTML_Insertion . Here are some examples that were discovered:
* libs/lc_switch.js#111

Is there a way to solve this? escaping html?
Thanks

**Comment by LCweb-ita** [comment]
The only potential custom strings are on/off texts. Sincerely to sanitize it as pure text could limit the plugin usability.
The end developer should sanitize initialized vales
